import type { Application } from "./types";

export const applications: Application[] = [
  {
    id: "1",
    company: "Google",
    role: "Software Engineer",
    location: "Mountain View, CA",
    jobPortal: "LinkedIn",
    appliedDate: "2026-07-28",
    status: "Applied",
    salary: "$150k – $180k",
  },
  {
    id: "2",
    company: "Stripe",
    role: "Backend Engineer",
    location: "Remote",
    jobPortal: "Company Website",
    appliedDate: "2026-07-22",
    status: "Interview",
    salary: "$160k – $200k",
  },
  {
    id: "3",
    company: "Netflix",
    role: "Senior Software Engineer",
    location: "Los Gatos, CA",
    jobPortal: "LinkedIn",
    appliedDate: "2026-07-15",
    status: "Applied",
    salary: "$180k – $220k",
  },
  {
    id: "4",
    company: "Airbnb",
    role: "Full Stack Engineer",
    location: "San Francisco, CA",
    jobPortal: "Wellfound",
    appliedDate: "2026-07-10",
    status: "Offer",
    salary: "$170k – $210k",
  },
  {
    id: "5",
    company: "Meta",
    role: "Frontend Engineer",
    location: "Menlo Park, CA",
    jobPortal: "Company Website",
    appliedDate: "2026-06-30",
    status: "Rejected",
    salary: "$175k – $205k",
  },
  {
    id: "6",
    company: "Amazon",
    role: "SDE II",
    location: "Seattle, WA",
    jobPortal: "Amazon Jobs",
    appliedDate: "2026-07-05",
    status: "Interview",
    salary: "$155k – $185k",
  },
  {
    id: "7",
    company: "Shopify",
    role: "React Developer",
    location: "Remote",
    jobPortal: "LinkedIn",
    appliedDate: "2026-07-18",
    status: "Applied",
  },
  {
    id: "8",
    company: "Uber",
    role: "iOS Engineer",
    location: "San Francisco, CA",
    jobPortal: "Glassdoor",
    appliedDate: "2026-06-20",
    status: "Ghosted",
  },
];
